language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abdullahpatni/react-doc -f Dockerfile.dev .

script:
  - docker run -e CI=true abdullahpatni/docker-react npm run test